Branch kashif
NotesCommunity/easy-notes pull request #16
Opened 2022-11-21 11:24 UTC by kashiflab

create note screen implemented

2022-11-21 12:39 UTC, hadiyarajesh commented
@kashiflab can you attach the UI (screenshot) if possible? That'll be helpful in review.

2022-11-21 13:04 UTC, kashiflab commented
**CreateNote Screen**

@hadiyarajesh 

![createnote](https://user-images.githubusercontent.com/68441963/203062089-f1bcefb7-c9c0-4759-8667-208a9f57a270.jpeg)

2022-11-24 06:36 UTC, hadiyarajesh requested changes

2022-11-24 06:36 UTC, hadiyarajesh commented on app/src/main/java/com/hadiyarajesh/easynotes/ui/createnote/CreateNoteScreen.kt
> +    darkTheme: Boolean = isSystemInDarkTheme(),
Why are we passing theme here? Compose will take care of it on its own AFAIK

2022-11-24 06:36 UTC, hadiyarajesh commented on app/src/main/java/com/hadiyarajesh/easynotes/ui/createnote/CreateNoteViewModel.kt
> +    val notes: Flow<PagingData<Note>> =
Foor creating a note, why we need paginated flow? We're supposed to create note here.

2022-11-24 06:36 UTC, hadiyarajesh commented on app/src/main/java/com/hadiyarajesh/easynotes/utility/GetMediaActivityResultContract.kt
> +            putExtra(Intent.EXTRA_MIME_TYPES, arrayOf("image/*", "video/*"))
We'll allow documents as well. But I understand this is for basic UI so no issues here.

2022-11-24 06:36 UTC, hadiyarajesh commented on app/src/main/res/drawable/ic_attach_file_24.xml
> +    android:viewportHeight="24" android:viewportWidth="24"
Need `Ctrl+Alt+L` here

2022-11-24 06:36 UTC, hadiyarajesh commented on app/src/main/res/drawable/ic_cancel_24.xml
> +    android:width="24dp" xmlns:android="http://schemas.android.com/apk/res/android">
Need `Ctrl+Alt+L` here

2022-11-24 06:36 UTC, hadiyarajesh commented on build.gradle.kts
> +    val compose_ui_version by extra("1.1.1")
Why are we adding compose version to project level build file? It's already defined in app level build file and working fine.

2022-11-28 07:15 UTC, kashiflab commented on app/src/main/java/com/hadiyarajesh/easynotes/ui/createnote/CreateNoteScreen.kt
> +    darkTheme: Boolean = isSystemInDarkTheme(),
I tried but some of the edit text fields filled color looks bad, that's why I used it

2022-11-28 07:16 UTC, kashiflab commented on app/src/main/java/com/hadiyarajesh/easynotes/ui/createnote/CreateNoteViewModel.kt
> +    val notes: Flow<PagingData<Note>> =
I just copied the repo, will change it while implementing

2022-11-28 07:16 UTC, kashiflab commented on app/src/main/java/com/hadiyarajesh/easynotes/utility/GetMediaActivityResultContract.kt
> +            putExtra(Intent.EXTRA_MIME_TYPES, arrayOf("image/*", "video/*"))
OK

2022-11-28 07:16 UTC, kashiflab commented on app/src/main/res/drawable/ic_attach_file_24.xml
> +    android:viewportHeight="24" android:viewportWidth="24"
Done

2022-11-28 07:17 UTC, kashiflab commented on app/src/main/res/drawable/ic_cancel_24.xml
> +    android:width="24dp" xmlns:android="http://schemas.android.com/apk/res/android">
Done

2022-11-28 07:26 UTC, kashiflab commented on build.gradle.kts
> +    val compose_ui_version by extra("1.1.1")
Removed & Fixed

2022-11-28 07:51 UTC, kashiflab commented
@hadiyarajesh now should I create a new PR in the master branch?

2022-11-28 08:14 UTC, hadiyarajesh commented on app/src/main/java/com/hadiyarajesh/easynotes/ui/createnote/CreateNoteScreen.kt
> +    darkTheme: Boolean = isSystemInDarkTheme(),
Got it. If I understood the requirement correctly, here's what you can do to avoid passing system theme

```kotlin
TextField(
	value = "",
	onValueChange = { },
	colors = TextFieldDefaults.textFieldColors(
		containerColor = MaterialTheme.colorScheme.background // or whatever you need
	)
)
```

2022-11-28 08:16 UTC, hadiyarajesh commented on app/src/main/java/com/hadiyarajesh/easynotes/ui/createnote/CreateNoteViewModel.kt
> +    val notes: Flow<PagingData<Note>> =
> @hadiyarajesh now should I create a new PR in the master branch?

Yes, please. Instead of creating a new one, you can point this PR to `master` as well.

2022-11-28 08:17 UTC, hadiyarajesh commented
> @hadiyarajesh now should I create a new PR in the master branch?

@kashiflab Yes, please. Instead of creating a new one, you can point this PR to `master` as well.

2022-11-28 11:05 UTC, kashiflab commented
> @kashiflab Yes, please. Instead of creating a new one, you can point this PR to `master` as well.

@hadiyarajesh  Please check, it is changed

2022-11-28 15:53 UTC, hadiyarajesh approved these changes
LGTM

2022-11-29 05:35 UTC, merged